# Numpy

In [1]:
import numpy as np

arr = np.array([1 , 2 , 3])
print("Array with Rank 1: \n" , arr)

# creando un array de rango 2 que corresponde con una matriz de dimension 2

arr = np.array([[1 , 2 , 3] , 
               [4 , 5 , 6]])
print("Array with Rank 2: \n" , arr)

# podemos acceder a elementos especificos de deichas matrices

index_arr = arr[[1] , [2]] # [fila] , [columna] [n + 1]
print(index_arr)

# podemos acceder a diferentes elementos a la vez

new_index_arr = arr[[0 , 1 , 1] , [0 , 1 , 2]] # elemento de el primer [a ,  b] , con el segundo [a* , b*]
print(new_index_arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]
[6]
[1 5 6]
